name: Update VMs

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Update Terraform (apply latest)
        run: |
          cd terraform
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Restart VMs to pick up new startup script
        run: |
          gcloud compute instances reset app-a --zone "${{ secrets.ZONE_A }}"
          gcloud compute instances reset app-b --zone "${{ secrets.ZONE_B }}"
